# Generated by Django 4.0.3 on 2022-04-09 00:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('size', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2)),
                ('map_type', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2)),
                ('biome', models.CharField(max_length=16)),
                ('terrain', models.CharField(max_length=16)),
                ('habitation', models.CharField(max_length=16)),
                ('parent_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.map')),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='parent_tile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='map.tile'),
        ),
        migrations.AddField(
            model_name='map',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.world'),
        ),
    ]
