# Generated by Django 4.0.3 on 2022-04-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_map_map_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='biome',
            field=models.CharField(choices=[('D', 'Desert'), ('G', 'Grassland'), ('O', 'Ocean')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tile',
            name='habitation',
            field=models.CharField(blank=True, choices=[('T', 'Town')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tile',
            name='terrain',
            field=models.CharField(blank=True, choices=[('F', 'Forest'), ('M', 'Mountain')], max_length=1, null=True),
        ),
    ]
