# Generated by Django 4.0.3 on 2022-04-10 01:36

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_tile_biome_alter_tile_habitation_and_more'),
    ]

    operations = [
        CreateExtension('postgis'),
    ]
