# Generated by Django 4.0.3 on 2022-04-10 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20220410_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tile',
            name='position',
        ),
    ]
