# Generated by Django 4.0.3 on 2022-04-13 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_world_owner'),
        ('map', '0007_tile_position'),
    ]

    operations = [
    ]
